export class CvCdoComparendo{
	constructor(
		public consecutivo:string,
		public fecha:any,
		public hora:string,
		public minutos:string,
		public direccion:string,
		public localidad:string,
		public observacionesAgente:string,
		public observacionesDigitador:string,
		public inmovilizacion:string,
		public accidente:string,
		public fuga:string,
		public retencionLicencia:string,
		public anulado:boolean,
		public fechaNotificacion:string,
		public infraccionValorAdicional:string,
		public gradoAlcoholemia:number,
		public licenciaTransitoNumero:string,
		public vehiculoPlaca:string,
		public vehiculoClase:string,
		public vehiculoServicio:number,
		public vehiculoRadioAccion:string,
		public vehiculoModalidadTransporte:number,
		public vehiculoTransportePasajero:number,
		public vehiculoTransporteEspecial:string,
		public idConsecutivo:number,
		public idMunicipioLugar:number,
		public idOrganismoTransitoLicencia:number,
		public idOrganismoTransitoMatriculado:number,
		public idFuncionario:number,
		public idInfraccion:number,
		public idSedeOperativaExpide:number,
		public id:number
	){}
} 