export class Comparendo{
	constructor(
		public consecutivo:string,
		public fecha:string,
		public horas:string,
		public minutos:string,
		public direccion:string,
		public localidad:string,
		public observacionesAgente:string,
		public observacionesDigitador:string,
		public inmovilizacion:string,
		public accidente:string,
		public fuga:string,
		public retencionLicencia:string,
		public fechaNotificacion:string,
		public infraccionValorAdicional:string,
		public licenciaTransitoNumero:string,
		public vehiculoPlaca:string,
		public vehiculoClase:string,
		public vehiculoServicio:string,
		public vehiculoRadioAccion:string,
		public vehiculoModalidadTransporte:string,
		public vehiculoTransportePasajero:string,
		public vehiculoTransporteEspecial:string,
		public consecutivoId:number,
		public municipioId:number,
		public tipoInfractorId:string,
		public funcionarioId:number,
		public infraccionId:number,
		public idSedeOperativaExpide:number,
		public id:number
	){}
} 