export class MsvRegistroIpat{
	constructor(

		/*public fechaRadicacion:string,
		public municipioId:number,
		public ciudadanoDemandadoId:number,
		public ciudadanoDemandanteId:number,*/
		public sedeOperativa:number,
		public gravedad:number,
		public lugar: string,
		public fechaAccidente:string,
		public fechaLevantamiento:string,
		public claseAccidente:number,
		public otroClaseAccidente:string,
		public choqueCon:number,
		public objetoFijo:number,
		public otroObjetoFijo:string,
		public area:number,
		public sector:number,
		public zona:number,
		public disenio:number,
		public estadoTiempo:number,
		public geometria:number,
		public utilizacion:number,
		public calzada:number,
		public carril:number,
		public material:number,
		public estadoVia:number,
		public condicionVia:number,
		public iluminacion:number,
		public estadoIluminacion:number,
		public visual:number,
		public visualDisminuida:number,

		//campos vehiculo
		public placa: string,
		public placaRemolque: string,
		public nacionalidadVehiculo: string,
		public marca: string,
		public linea: string,
		public color: string,
		public modelo: string,
		public carroceria: string,
		public ton: string,
		public pasajeros: string,
		public numeroLicenciaTransito: string,
		
		public empresa:number,
		public nitEmpresa: number,
		
		public matriculadoEn: string,
		public inmovilizadoEn: string,
		public aDisposicionDe: string,
		public tarjetaRegistro: string,
		
		//revision tecnomecanica
		public revisionTecnomecanica: string,
		public numeroTecnoMecanica: number,
		public cantidadAcompaniantes: number,
		
		//soat
		public portaSoat: string,
		public soat:number,
		public numeroPoliza: number,
		public aseguradoraSoat: string,
		public fechaVencimientoSoat: string,
		
		//seguro de responsabilidad civil contractual
		public portaSeguroResponsabilidadCivil: string,
		public numeroSeguroResponsabilidadCivil: number,
		public aseguradoraSeguroResponsabilidadCivil: string,
		public fechaVencimientoSeguroResponsabilidadCivil: string,
		
		//seguro de responsabilidad extracontractual
		public portaSeguroExtracontractual: string,
		public numeroSeguroExtracontractual: number,
		public aseguradoraSeguroExtracontractual: string,
		public fechaVencimientoSeguroExtracontractual: string,
		
		//propietario
		public mismoConductor: string,
		public nombresPropietario: string,
		public apellidosPropietario: string,
		public tipoIdentificacionPropietario: string,
		public identificacionPropietario: number,

		public clase:number,
		public servicio:number,
		public modalidadTransporte:number,
		public radioAccion:number,
		public descripcionDanios: string,
		public falla: number,
		public lugarImpacto: number,
		
		//Datos Conductor
		public nombresConductor: string,
		public apellidosConductor: string,
		public tipoIdentificacionConductor: string,
		public identificacionConductor: number,
		public nacionalidadConductor: string,
		public fechaNacimientoConductor: string,
		public sexoConductor: string,
		public gravedadConductor: number,
		public direccionResidenciaConductor: string,
		public ciudadResidenciaConductor: number,
		public telefonoConductor: number,
		public praticoExamenConductor: string,
		public autorizoConductor: string,
		public resultadoExamenConductor: string,
		public gradoExamenConductor: string,
		public sustanciasPsicoactivasConductor: string,
		public portaLicencia: string,
		public numeroLicenciaConduccion: number,
		public categoriaLicenciaConduccion: string,
		public restriccionConductor: string,
		public fechaExpedicionLicenciaConduccion: string,
		public fechaVencimientoLicenciaConduccion: string,
		public chalecoConductor: string,
		public cascoConductor: string,
		public cinturonConductor: string,
		public hospitalConductor:number,
		public descripcionLesion: string,


		//datos victima
		public victima: string,
		public nombresVictima: string,
		public apellidosVictima: string,
		public tipoIdentificacionVictima: string,
		public identificacionVictima: string,
		public nacionalidadVictima: string,
		public fechaNacimientoVictima: string,
		public sexoVictima: string,
		public direccionResidenciaVictima: string,
		public ciudadResidenciaVictima: string,
		public telefonoVictima: string,
		public hospitalVictima: number,
		public praticoExamenVictima: string,
		public autorizoVictima: string,
		public resultadoExamenVictima: string,
		public gradoExamenVictima: string,
		public sustanciasPsicoactivasVictima: string,
		public chalecoVictima: string,
		public cascoVictima: string,
		public cinturonVictima: string,
		public tipoVictima:number,
		public gravedadVictima:number,

		public observaciones:string,

		// datos de quien conoce el accidente
		public gradoTestigo: string,
		public nombresTestigo: string,
		public apellidosTestigo: string,
		public tipoIdentificacionTestigo: number,
		public identificacionTestigo: number,
		public placaTestigo: string,
		public entidadTestigo: string,

		public hipotesis: number,

		/*public limitacionId:number,
		public tipoProcesoId:number,
		public entidadJudicialId:number,
		public causalLimitacionId:number,
		public datos:string,*/
	){}
}