export class MsvIpatConductor {
    constructor(
        public nombresConductor: string,
		public apellidosConductor: string,
		public tipoIdentificacionConductor: string,
		public identificacionConductor: string,
		public nacionalidadConductor: string,
		public fechaNacimientoConductor: string,
		public sexoConductor: string,
		public idGravedadConductor: number,
		public direccionResidenciaConductor: string,
		public ciudadResidenciaConductor: number,
		public telefonoConductor: string,
		public practicoExamenConductor: string,
		public autorizoConductor: string,
		public idResultadoExamenConductor: string,
		public idGradoExamenConductor: string,
		public sustanciasPsicoactivasConductor: string,
		public portaLicencia: string,
		public numeroLicenciaConduccion: number,
		public categoriaLicenciaConduccion: string,
		public restriccionConductor: string,
		public fechaExpedicionLicenciaConduccion: string,
		public fechaVencimientoLicenciaConduccion: string,
		public organismoTransito: string,
		public chalecoConductor: string,
		public cascoConductor: string,
		public cinturonConductor: string,
		public idHospitalConductor:number,
        public descripcionLesionConductor: string,
    ){}
}