export class MsvIpatVictima {
    constructor(
        public victima: string,
        public nombresVictima: string,
        public apellidosVictima: string,
        public tipoIdentificacionVictima: string,
        public identificacionVictima: string,
        public nacionalidadVictima: string,
        public fechaNacimientoVictima: string,
        public sexoVictima: string,
        public direccionResidenciaVictima: string,
        public ciudadResidenciaVictima: string,
        public telefonoVictima: string,
        public idHospitalVictima: string,
        public placaVehiculoVictima: string,
        public practicoExamenVictima: string,
        public autorizoVictima: string,
        public idResultadoExamenVictima: string,
        public idGradoExamenVictima: string,
        public sustanciasPsicoactivasVictima: string,
        public chalecoVictima: string,
        public cascoVictima: string,
        public cinturonVictima: string,
        public idTipoVictima: number,
        public idGravedadVictima: number,
        public descripcionLesionVictima: string,
    ) {}
}