export class RnaPreregistro{
	constructor(
		public id:number,
		public claseId:number,
		public municipioId:number,
		public lineaId:number,
		public servicioId:number,
		public colorId:number,
		public carroceriaId:number,
		public combustibleId:number,
		public radioAccionId:number,
		public modalidadTransporteId:number,
		public sedeOperativaId:number,
		public placa:string,
		public numeroFactura:string,
		public fechaFactura:string,
		public valor:string,
		public numeroManifiesto:string,
		public fechaManifiesto:string,
		public cilindraje:string,
		public modelo:string,
		public motor:string,
		public chasis:string,
		public serie:string,
		public vin:number,
		public numeroPasajeros:number,
		public pignorado:number,
		public cancelado:number,
		public tipoVehiculo:string,
		public transportePasajeros:string,
	){}
}