export class RnaPreregistro{
	constructor(
		public id:number,
		public numeroFactura:string,
		public fechaFactura:string,
		public valor:string,
		public placa:any,
		public MarcaId: number,
		public lineaId:number,
		public clase:number,
		public carroceriaId:number,
		public servicioId:number,
		public colorId:number,
		public combustibleId:number,
		public sedeOperativaId:number,
		public numeroManifiesto:string,
		public municipioId:number,
		public fechaManifiesto:string,
		public cilindraje:string,
		public modelo:string,
		public motor:string,
		public chasis:string,
		public serie:string,
		public vin:number,
		public numeroPasajeros:number,
		public tipoMatricula:string,
		public capacidadCarga:number,
		public radioAccionId:number,
		public modalidadTransporteId:number,
		
	){}
}