export class VhloRnaPreregistro{
	constructor(
		public numeroFactura:string,
		public fechaFactura:string,
		public valor:string,
		public placa:any,
		public numeroManifiesto:string,
		public fechaManifiesto:string,
		public cilindraje:string,
		public modelo:string,
		public motor:string,
		public chasis:string,
		public serie:string,
		public vin:string,
		public numeroEjes:number,
		public numeroPasajeros:number,
		public tipoMatricula:string,
		public radicado:any,
		public capacidadCarga:number,
		public idMarca: number,
		public idLinea:number,
		public idClase:number,
		public idCarroceria:number,
		public idServicio:number,
		public idColor:number,
		public idCombustible:number,
		public idOrganismoTransito:number,
		public idRadioAccion:number,
		public idModalidadTransporte:number,
		public idEmpresa:number,
		public id:number,
	){}
}