export class SvCaracterizacion{
	constructor(
		public id:number,
		public nit:number,		
		public fecha: string,
		public municipio: string,
		public nombres: string,
		public apellidos: string,
		public identificacion: number,
		public clc: string,
		public fechaVigencia: string,
		public edad: number,
		public genero: string,
		public grupoTrabajo: string,
		public otroGrupoTrabajo: string,
		public tipoContrato: string,
		public otroTipoContrato: string,
		public cargo: string,
		public experienciaConduccion: string,
		public accidente: string,
		public circunstancias: string,
		public incidente: string,
		public frecuenciaDesplazamiento: string,
		public propioVehiculo: string,
		public desplazamientoPlanificado: string,
		public antelacion: string,
		public medioDesplazamiento: string,
		public trayecto: number,
		public tiempoTrayecto: string,
		public kmMensualTrayecto: string,
		public arrayFactoresRiesgo: string,
		public otroFactorRiesgo: string,
		public arrayCausasRiesgo: string,
		public otraCausaRiesgo: string,
		public riesgoPercibido: string,
		public propuestaReduccion: string,
	){}
}