export class VhloRnmaPreregistro{
	constructor(
		public placa: string,
		public serie: string,
		public vin: string,
		public chasis: string,
		public motor: string,
		public modelo: string,
		public idColor: number,
		public idLinea: number,
		public idCarroceria: number,
		public idCombustible: number,
		public fechaIngreso: string,
		public peso: string,
		public cargaUtilMaxima: string,
		public numeroLlantas: string,
		public numeroEjes: string,
		public alto: string,
		public ancho: string,
		public largo: string,
		public tipoDispositivo: number,
		public numeroImportacion: string,
		public numeroActivacionGps: string,
		public numeroFactura: number,
		public fechaFactura: string,
		public valor: string,
		public tipoMatricula: string,
		public idSubpartidaArancelaria: number,
		public idTipoRodaje: number,
		public idTipoCabina: number,
		public idClaseMaquinaria: number,
		public idCondicionIngreso: number,
		public idOrigenRegistro: number,
		public idEmpresaGps: number,
		public idOrganismoTransito: number,
		public id: number,
	){}
}