export class SvIpatConductor {
    constructor(
        public consecutivo: string,

        public nombres: string,
		public apellidos: string,
		public tipoIdentificacion: string,
		public identificacion: string,
		public nacionalidad: string,
		public fechaNacimiento: string,
		public sexo: string,
		public idGravedad: number,
		public direccionResidencia: string,
		public ciudadResidencia: number,
		public telefono: string,
		public placaVehiculo: string,
		public practicoExamen: string,
		public autorizo: string,
		public idResultadoExamen: string,
		public idGradoExamen: string,
		public sustanciasPsicoactivas: string,
		public portaLicencia: string,
		public numeroLicenciaConduccion: number,
		public categoriaLicenciaConduccion: number,
		public restriccion: string,
		public fechaExpedicionLicenciaConduccion: string,
		public fechaVencimientoLicenciaConduccion: string,
		public organismoTransito: string,
		public chaleco: string,
		public casco: string,
		public cinturon: string,
		public idHospital:number,
        public descripcionLesion: string,
    ){}
}